import json
import pickle
import os
from pathlib import Path
from typing import List, Tuple, Dict, Any

import faiss
import numpy as np
from sklearn.preprocessing import normalize
from sentence_transformers import SentenceTransformer

from config import JSON_RAG_TEXT_KEY

os.environ["OMP_NUM_THREADS"] = "1"
os.environ["MKL_NUM_THREADS"] = "1"

FAISS_INDEX_FILE_NAME = "faiss.index"
TEXTS_FILE_NAME = "texts.pkl"
DOCS_FILE_NAME = "docs.pkl"
DEVICE = 'cpu'


class IndexBuilder:
    """
    A class for building and saving a FAISS index based on text embeddings
    generated by a SentenceTransformer model.

    Attributes:
        embedder (SentenceTransformer): Model used to generate text embeddings.
        index (faiss.IndexFlatIP): The FAISS index.
        texts (List[str]): List of text inputs indexed.
        docs (List[Dict[str, Any]]): Original documents used for indexing.
    """

    def __init__(self, model_name: str):
        """
        Initializes the IndexBuilder with a specified embedding model.

        Args:
            model_name (str): The name or path of the SentenceTransformer model.
        """
        self.embedder = SentenceTransformer(model_name, device=DEVICE)
        self.index = None
        self.texts = []
        self.docs = []

    def build_index(self, docs: List[Dict[str, Any]]) -> Tuple[faiss.IndexFlatIP, np.ndarray, List[str]]:
        """
        Builds a FAISS index from a list of documents and stores it in the object.

        Args:
            docs (List[Dict[str, Any]]): List of documents with text under JSON_RAG_TEXT_KEY.

        Returns:
            Tuple[faiss.IndexFlatIP, np.ndarray, List[str]]: FAISS index, embeddings, and list of texts.
        """
        self.docs = docs
        self.texts = [doc[JSON_RAG_TEXT_KEY] for doc in docs]
        embeddings = self.embed_texts(self.texts)

        self.index = faiss.IndexFlatIP(embeddings.shape[1])
        self.index.add(embeddings.astype("float32"))

        return self.index, embeddings, self.texts

    def save_index(self, index: faiss.IndexFlatIP, texts: List[str], docs: List[Dict[str, Any]], dir: Path) -> None:
        """
        Saves the FAISS index, texts, and original documents to the specified directory.

        Args:
            index (faiss.IndexFlatIP): The FAISS index to save.
            texts (List[str]): The list of text entries.
            docs (List[Dict[str, Any]]): The original documents.
            dir (Path): Directory to save the data.
        """
        dir.mkdir(parents=True, exist_ok=True)

        faiss.write_index(index, os.path.join(dir, FAISS_INDEX_FILE_NAME))

        with open(os.path.join(dir, TEXTS_FILE_NAME), "wb") as f:
            pickle.dump(texts, f)

        with open(os.path.join(dir, DOCS_FILE_NAME), "wb") as f:
            pickle.dump(docs, f)

    def load_index(self, dir: Path) -> None:

        self.index = faiss.read_index(os.path.join(dir, FAISS_INDEX_FILE_NAME))
        self.texts = self._load_pickle(os.path.join(dir, TEXTS_FILE_NAME))
        self.docs = self._load_pickle(os.path.join(dir, DOCS_FILE_NAME))

    def search(self, query_vec: np.ndarray, top_k: int) -> List[Dict[str, Any]]:
        """
        Searches the index with a query vector and returns the top_k closest documents.

        Args:
            query_vec (np.ndarray): Query embedding vector.
            top_k (int): Number of results to return.

        Returns:
            List[Dict[str, Any]]: List of closest matching documents.
        """
        if self.index is None:
            raise ValueError("FAISS index is not loaded or built.")

        query_vec = np.array(query_vec).astype("float32")
        if query_vec.ndim == 1:
            query_vec = query_vec.reshape(1, -1)

        _, indices = self.index.search(query_vec, top_k)
        return [self.docs[i] for i in indices[0]]

    def embed_texts(self, texts: List[str]) -> np.ndarray:

        embeddings = self.embedder.encode(texts, normalize_embeddings=True)
        return normalize(embeddings, norm='l2')

    def _load_pickle(self, path: str) -> Any:

        with open(path, "rb") as f:
            return pickle.load(f)
